<a href="https://colab.research.google.com/github/JaiswalFelipe/Learning-Python/blob/main/NumpyPart1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numeric Python**
Documentation: numpy.org

In [ ]:
import numpy as np

### **N-D array**
- Point "." Represents object Oth dimension (Single Data point) 0-D array
- Line "___" " " " 1st dimension (Sequence of points) 1-D array
- Plane      " " " 2nd dimension (Sequence of infinitely many lines placed next to one another) 2-D array: collection of 1-D sequences
- Arrays == Vectors (Linear Algebra)
- N-Dimensional array: N --> Natural Numbers
- N of opening/closing brackets == N-dimensions 

In [ ]:
array_2D = np.array([[1,2,3],[ 4,5,6]])
print(array_2D)
print(type(array_2D))

# Two 1D arrays each containing exactly 3 elements (2x3 table: 2 Rows and 3 Cols)
print(array_2D.shape)  

# You can index the shape
print("")
print(array_2D.shape[0]) # How many rows
print(array_2D.shape[1]) # How many cols

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)

2
3


##### Arrays and Lists

In [ ]:
# Plug in lists as inputs of the np.array() function
list_a = [[4,5,7],[9,3,1]]
print(list_a) # Lists showcase all the values in a single line (does not have shape)

array_a = np.array(list_a)

print("")
print(array_a) # While arrays stack them like a table with 2 rows and 3 cols (have shape)

[[4, 5, 7], [9, 3, 1]]

[[4 5 7]
 [9 3 1]]


In [ ]:
# Array Operations works elementwise while list ops don't
list_b = list_a[0] + list_a[1]
array_b = array_a[0] + array_a[1]

print(list_b) # List concats
print("")
print(array_b) # Array sums (each col == elementwise)

[4, 5, 7, 9, 3, 1]

[13  8  8]


In [ ]:
# Mathematical functions
np.sqrt(array_a)

array([[2.        , 2.23606798, 2.64575131],
       [3.        , 1.73205081, 1.        ]])

### **Numpy Fundamentals**

##### Indexing
- Like many other programming languages, python uses 0 indexing
- When working with 2D arrays, ROWS == ELEMENETS, 
- SEPARATE NUMERIC VALS == INDIVIDUAL ELEMENTS 

In [ ]:
print(array_a)
print("")

# Specific values
print(array_a[0])
print("")
print(array_a[1])

[[4 5 7]
 [9 3 1]]

[4 5 7]

[9 3 1]


In [ ]:
# INDIVIDUAL ELEMENTS
# "Second" element of row "one"
print(array_a[0][1])

# Is the same as:

print(array_a[0,1])

5
5


In [ ]:
# Slicing: Go through all the rows from this column
# all the first "individual" elements of the 2 rows
array_a[:,0]

array([4, 9])

In [ ]:
# Negative indices: Traversing the array backwards

# Last element
print(array_a[-1])

# Last "individual" element of the last element
print(array_a[-1][-1])

# Last "individual" elements of the Rows
print(array_a[:,-1])

[9 3 1]
1
[7 1]


##### Assigning Values

In [ ]:
array_a

array([[4, 5, 7],
       [9, 3, 1]])

In [ ]:
# Alter individual elements within an array
# I.E. Set the 3rd individual element of the first row to a different number
array_a[0,-1] = 5

# Set individual elements of the 2nd row to 0
array_a[-1] = 0

print(array_a)

[[4 5 5]
 [0 0 0]]


In [ ]:
# Using list to set individual values
list_a = [1,2,3]

array_a[0] = list_a
array_a

array([[1, 2, 3],
       [0, 0, 0]])

In [ ]:
# Go through all the rows and assign each one the same value
array_a[:] = 5
array_a

array([[5, 5, 5],
       [5, 5, 5]])

##### Elementwise Properties
- Whatever mathematical computation we are conducting, we are doing it to each element of the array

In [ ]:
array_a

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
array_a + 2

array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
# Elementwise Addition
# Each individual element is added up with its corresponding counterpart from the other array
array_b

[13  8  8]


In [ ]:
array_a[0] * array_b

array([65, 40, 40])

In [ ]:
# Conduct operations between arrays of different dimensions
# NOTE: The shapes of the arrays need to be compatible, 
# The length of the 1-D array must match the "length" of the 2_D array
array_c = np.array([[1,2,3],[5,6,7]])

array_a + array_c

array([[ 6,  7,  8],
       [10, 11, 12]])

##### Types of Data Supported by NumPy
- Arrays can contain numbers (All Numerical datatypes)


In [ ]:
array_d = np.array([[1,2,3],[5,6,7]], dtype = "float32") # 32 bits of memory for each element of the array
array_d

array([[1., 2., 3.],
       [5., 6., 7.]], dtype=float32)

In [ ]:
# Is the same as:
array_d = np.array([[1,2,3],[5,6,7]], dtype = np.float16) # 16 bits of memory for each element of the array
array_d

array([[1., 2., 3.],
       [5., 6., 7.]], dtype=float16)

In [ ]:
# Booleans
# Anything different from 0 is equated to "True" when using Booleans
array_d = np.array([[1,2,0],[5,6,7]], dtype = np.bool) 
array_d

array([[ True,  True, False],
       [ True,  True,  True]])

In [ ]:
# Str
array_d = np.array([[1,2,0],[5,6,7]], dtype = np.str)  # dtype='<U1' == Unicode values of length up to 1 
array_d

array([['1', '2', '0'],
       ['5', '6', '7']], dtype='<U1')

In [ ]:
# Str: dtype='<U2' == Unicode values of length up to 2 
array_d = np.array([[11,2,0],[5,6,7]], dtype = np.str)  # "11" first indiv. element of the first element/row
array_d

array([['11', '2', '0'],
       ['5', '6', '7']], dtype='<U2')

### **Characteristics of NumPy Functions**
- Universal Functions:
  - Work with NDarrays on an element-by-element bases
  - An extension of the elementwise operations
  - Mathematical operations, trigonomentric functions, comparison functions
  - Supports Broadcasting, Typecasting, Computing over a given axis

##### BROADCASTING
- Conduct elementwise operations BUT have elements of diff sizes, and/or dimensions
- We can broadcast the smaller variable and create a broadcasted version with the size of the larger one

In [ ]:
array_a = np.array([1,2,3])
array_b = np.array([[1],[2]])
matrix_c = np.array([[1,2,3],[4,5,6]])

print(array_a)
print("")
print(array_b)
print("")
print(matrix_c)

[1 2 3]

[[1]
 [2]]

[[1 2 3]
 [4 5 6]]


In [ ]:
# Add array_a to each row of matrix_c
# Here, we're broadcasting the array to a 2x3 matrix 
np.add(array_a,matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

##### TYPECASTING
- Taking every element of an array and changing it to a specified datatype
- Widely used
- The preferred way to unify datatypes across a project

In [ ]:
np.add(array_a,matrix_c, dtype = np.float64)

array([[2., 4., 6.],
       [5., 7., 9.]])

##### Computing over a given axis
We can use this feature to run a function along each row or column

In [ ]:
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# axis = 0: Find the mean of each "column" of the array
np.mean(matrix_c, axis = 0)

array([2.5, 3.5, 4.5])

In [ ]:
# axis = 1: Find the mean of each "row" of the array
np.mean(matrix_c, axis = 1)

array([2., 5.])

### **Working with Arrays**
- Highlights:
  - Slicing
  - np.squeeze()

##### Basic Slicing
- Creating a new array by taking chunks of values out of an existing array
- Slices are just smaller arrays
- Slicing = interval indexing

In [ ]:
matrix_d = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
matrix_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix_d[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# No data
matrix_d[0:0]

array([], shape=(0, 3), dtype=int64)

In [ ]:
# First row of the matrix
# Starts at Index 0 and stops before the row of index 1
matrix_d[0:1]

array([[1, 2, 3]])

In [ ]:
# Starts at Index 0 and stops before the row of index 2
matrix_d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Starts at Index 1
matrix_d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Negative slicing
# Upto but not including the last row
matrix_d[:-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# First ":" is about rows (first dimension)
# After the "," is about columns (2nd dimension)
# So all the rows, and starting from the 2nd column (index 1)
matrix_d[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

##### Stepwise Slicing
[1:10:3] where 1 is the start, 10 is the end, and 3 is the step
- The step argument can be + or - but not 0

In [ ]:
matrix_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix_d[::2,::]

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
matrix_d[::,::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [ ]:
# Every "2nd" value of the rows
matrix_d[::2,::2]

array([[1, 3],
       [7, 9]])

##### Conditional Slicing
- To filter out certain data

In [ ]:
matrix_e = np.array([[1,2,3,4,6],[3,7,3,1,2],[4,2,1,5,6]])
matrix_e

array([[1, 2, 3, 4, 6],
       [3, 7, 3, 1, 2],
       [4, 2, 1, 5, 6]])

In [ ]:
# All the first columns ",0" of all the rows ":"
matrix_e[:,0]

array([1, 3, 4])

In [ ]:
# Now with condition
matrix_e[:,0] > 2

array([False,  True,  True])

In [ ]:
matrix_e[:,:] > 2

array([[False, False,  True,  True,  True],
       [ True,  True,  True, False, False],
       [ True, False, False,  True,  True]])

In [ ]:
# All the values of matrix_c which is greater than 2
matrix_e[matrix_e[:,:] > 2]

array([3, 4, 6, 3, 7, 3, 4, 5, 6])

In [ ]:
# All the even numbers
matrix_e[matrix_e[:,:] % 2 == 0]

array([2, 4, 6, 2, 4, 2, 6])

In [ ]:
# Multiple Conditions "&" == "and"
# All the "even" numbers which are "lesser than or equal" to 4
matrix_e[(matrix_e[:,:] % 2 == 0) & (matrix_e[:,:] <= 4)]

array([2, 4, 2, 4, 2])

##### Dimensions and the Squeeze Function
- Removes all the "unnecessary dimensions" of an array
- When we squeeze an array (holding a single value) along all its axes, we get a single numeric value

In [ ]:
matrix_e

array([[1, 2, 3, 4, 6],
       [3, 7, 3, 1, 2],
       [4, 2, 1, 5, 6]])

In [ ]:
# The method: .squeeze()
matrix_e[0:1,0:1].squeeze()

array(1)

In [ ]:
matrix_e[0:1,0:1].squeeze().shape

()

In [ ]:
# The Equivalent Function: np.squeeze(var_name)
np.squeeze(matrix_e[0:1,0:1])

array(1)

### **Generating Data with Numpy**
- Highlights: 
  - _like functions
  - np.arange()
  - Random Generators and Seeds
  - .choice

##### Arrays of 0s and 1s

In [ ]:
# np.empty() returns an array without initializing entries
# Fastest way to generate an N-D array
empty_array = np.empty(shape = (2,3))
empty_array

array([[4.63837304e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
# np.zeros() creates an array full of 0s
# Can set the datatype like so:
array_0s = np.zeros(shape = (2,3), dtype = np.int8)
array_0s

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [ ]:
# np.ones() creates an array full of 1s
array_1s = np.ones(shape = (2,3))
array_1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# np.full() generates an array filled entirely with specified value
# fill_value takes 'scalar' values, therefore you can set it to str
array_full = np.full(shape = (2,3), fill_value = 2)
array_full

array([[2, 2, 2],
       [2, 2, 2]])

##### _like functions
- == to the np.empty,zeros,ones,full but don't need to specify a shape or type
- We need to provide another array (whose shape and type we take)
- Why are _like functions useful?
 - Creates a 2nd array where we store a value or each element of the original one
 - Convinient when working with huge databases (faster loading times)

In [ ]:
matrix_A = np.array([[1,2,3,4,5],[4,5,6,7,8],[0,2,1,6,8]])
matrix_A

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8],
       [0, 2, 1, 6, 8]])

In [ ]:
# Pass matrix_A as input
array_empty_like = np.empty_like(matrix_A)
array_empty_like

array([[93881692908928,   210453397554,   206158430253,   193273528374,
          240518168626],
       [  206158430292,   249108103224,   214748364849,   219043332154,
          197568495670],
       [  244813135926,   227633266745,   240518168631,             90,
                     0]])

In [ ]:
# Application of "np.zeros_like" in analysis:  
# 1. Starting point for a planner 
# 2. A "switch" where we change the values from 0-1 (and back)
# Really useful when working with dummy variables
# 
array_0s_like = np.zeros_like(matrix_A)
array_0s_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

##### A Non-Random Sequence of Numbers
- np.arange() == array range == np's equivalent of Python's range function
- By default: creates a sequence of consecutive integer values within a given range
- array range outputs an array
- start - stop - step

In [ ]:
# Python's "range"
list(range(30))  # Warning! Outputs a long vertical list

In [ ]:
# nps "arange"
array_rng = np.arange(3)
array_rng

array([0, 1, 2])

In [ ]:
# WHen stop argument is not provided: stop == start, and switches the origin to "0"
array_rng = np.arange(start = 30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
# So specify
array_rng = np.arange(start = 0, stop = 30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
# With "step"
array_rng = np.arange(start = 0, stop = 30, step = 2.5)
array_rng

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

In [ ]:
# You can also set the data type
# Because of "int32" our stepsize is set to "2", that's why there's only 12 values outputed because step 2.5 has only 12 values
array_rng = np.arange(start = 0, stop = 30, step = 2.5, dtype = np.int32)
array_rng

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22], dtype=int32)

##### Random Generators and Seeds
- SEED - a set of starting parameters for the algorithm
- Everytime we call a method, the Generator randomly selects a "seed"

In [ ]:
# This allows us to use the generator and pcg without having to write their full name all the time
# like so: numpy.random.Generator() and numpy.random.PCG64()
# The "Generator function" takes a "bit generator" as an input and creates generator objects
# PCG == Permutation Congruential Generator contains function pointers that can produce values of up to 64 bits in size
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [ ]:
array_RG = gen(pcg())
array_RG.normal() # Generates a value from a "Normal Distribution"

-2.4220442620928657

In [ ]:
array_RG = gen(pcg())
array_RG.normal(size = 5)

array([ 0.85337027,  1.67194058,  0.18540428, -0.17236003,  0.51523516])

In [ ]:
array_RG = gen(pcg())
array_RG.normal(size = (5,5))

array([[-2.32308322,  1.06744012,  1.22753988, -0.33103143,  0.31979892],
       [ 0.09108742,  0.44674873,  0.2693962 , -0.02230973,  1.08597386],
       [-0.29013409, -0.15396823,  0.20930025,  0.3936152 ,  1.55035939],
       [-1.3341902 , -0.29383833, -0.10207863,  0.85958973,  0.18179991],
       [-0.48551752,  0.35709392, -0.24772855,  0.31331091,  0.49183655]])

In [ ]:
# SEED - a set of starting parameters for the algorithm
# Everytime we call a method, the Generator randomly selects a "seed"

# Specify a seed for the Generator object
# Rerunning this cell will output the same values because of the "seed"
array_RG = gen(pcg(seed = 365))
array_RG.normal(size = (5,5))

# A seed only lasts for one execution of a method or function before it is reset
# Running "array_RG.normal(size = (5,5))" to a different cell will again result different values
# So whenever we intend to use a seed, we'll have to reset it every time

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

##### Basic Random Functions in NumPy
- numpy.integers()
- numpy.random()
- numpy.choice() Most useful

In [ ]:
#from numpy.random import Generator as gen
#from numpy.random import PCG64 as pcg

In [ ]:
# numpy.integers() generates whole numbers
# Requires defining a fixed range of values to choose from
array_RG = gen(pcg(seed = 365))
array_RG.integers(10, size = (5,5))

array([[0, 7, 6, 7, 8],
       [6, 6, 2, 0, 6],
       [3, 0, 3, 7, 9],
       [1, 1, 8, 7, 4],
       [4, 8, 6, 4, 9]])

In [ ]:
# 2 digit numbers
array_RG = gen(pcg(seed = 365))
array_RG.integers(low = 10, high = 100, size = (5,5))

array([[16, 80, 72, 19, 43],
       [23, 36, 46, 54, 75],
       [53, 30, 66, 43, 59],
       [14, 68, 28, 13, 58],
       [74, 74, 86, 37, 25]])

In [ ]:
# numpy.random() always between 0 and 1
array_RG = gen(pcg(seed = 365))
array_RG.random(size = (5,5)) 

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736],
       [0.29787156, 0.4996155 , 0.4865245 , 0.62740703, 0.54952637],
       [0.64894629, 0.04411757, 0.7206516 , 0.84594003, 0.17159792]])

In [ ]:
# numpy.choice() simulates the idea of making an arbitrary choice out of a given sequence
# Most useful
array_RG = gen(pcg(seed = 365))
array_RG.choice([1,2,3,4,5], size = (5,5)) 

array([[1, 4, 4, 4, 5],
       [4, 4, 2, 1, 4],
       [2, 1, 2, 4, 5],
       [1, 1, 5, 4, 3],
       [3, 5, 4, 3, 5]])

In [ ]:
# You can manually set the "probabilities" p of each value of the sequence
# But the length should be equal otherwise "error"
# Notice the "p" argument: THEIR SUM SHOULD EQUAL TO 1
array_RG = gen(pcg(seed = 365))
array_RG.choice([1,2,3,4,5], p = [0.1,0.1,0.1,0.1,0.6], size = (5,5)) 

array([[5, 5, 5, 3, 5],
       [1, 5, 2, 5, 5],
       [5, 5, 1, 5, 4],
       [3, 5, 5, 5, 5],
       [5, 1, 5, 5, 2]])

##### Probability Distributions in NumPy
- Poisson
- Binomial
- Logistic

In [ ]:
#from numpy.random import Generator as gen
#from numpy.random import PCG64 as pcg

# "poisson" method
array_RG = gen(pcg(seed = 365))
array_RG.poisson(size = (5,5))

# The arrays is 0s, 1s, and 2s because the default value of lambda == 1
# This means that over a fixed interval of time, distance, or space we expect an event to occur "exactly" once

array([[2, 0, 1, 1, 2],
       [1, 1, 0, 1, 1],
       [1, 2, 1, 1, 0],
       [0, 1, 0, 2, 1],
       [0, 1, 0, 0, 2]])

In [ ]:
# Set the lambda
# Notice the "lam" argument
array_RG = gen(pcg(seed = 365))
array_RG.poisson(lam = 10, size = (5,5))

array([[11, 12, 12, 14, 13],
       [ 9, 10, 11, 11,  8],
       [11,  8, 10,  9, 14],
       [ 7,  8,  9, 15, 15],
       [13,  8,  8,  7,  9]])

In [ ]:
# Binomial distribution measures how many times a certain outcome can appear over a series of trials
# where there are "only 2" possible outcomes
# n argument: number of trials
# p argument: probability of getting our desired outcome
array_RG = gen(pcg(seed = 365))
array_RG.binomial(n = 100, p = 0.4, size = (5,5))

# Each element is the number of times (out of 100) we've gotten our preferred outcome
# On avg, most of outcomes are around "40"
# 40% proba of getting what we want on each of the 100 indiv trials

array([[42, 44, 30, 36, 45],
       [36, 41, 38, 42, 41],
       [35, 31, 35, 46, 29],
       [41, 41, 46, 34, 48],
       [45, 45, 45, 40, 43]])

In [ ]:
# Logistic
# Notice: loc == Location, and scale
array_RG = gen(pcg(seed = 365))
array_RG.logistic(loc = 9, scale = 1.2, size = (5,5))

array([[10.37767822, 10.42451863,  9.63404367,  7.36153427,  9.82286787],
       [ 5.81223125, 10.09354231,  6.46790532, 11.38740256,  8.97147918],
       [10.85844698,  8.79081317,  5.962079  ,  9.99560681,  8.34539118],
       [ 7.97105522,  8.9981544 ,  8.93530194,  9.6253307 ,  9.23850869],
       [ 9.73729284,  5.3090678 , 10.13723528, 11.04372782,  7.11078651]])

# **Applications of Random Data in NumPy**
- **Test Creation**: When real data isn't available, we sometimes need pseudo-random data to test how well a program performs


In [ ]:
# Test Creation example:
# Generate 5 different arrays
# Create a bigger array with all of them in it
# Export to CSV
array_RG = gen(pcg(seed = 365))

array_column_1 = array_RG.normal(loc = 2, scale = 3, size = (1000))
array_column_2 = array_RG.normal(loc = 7, scale = 2, size = (1000))
array_column_3 = array_RG.logistic(loc = 11, scale = 3, size = (1000))
array_column_4 = array_RG.exponential(scale = 4, size = (1000))
array_column_5 = array_RG.geometric(p = 0.7, size = (1000))

In [ ]:
# Step 1: Generate 5 different arrays
random_test_data = np.array([array_column_1, 
                             array_column_2,
                             array_column_3,
                             array_column_4,
                             array_column_5]).transpose() # Transposing a matrix means transposing rows into columns (and vice versa)

random_test_data

array([[ 1.59077303,  6.42174295, 10.14698427,  6.91500737,  1.        ],
       [ 2.28243293,  8.57902322, 15.93309953,  6.243605  ,  1.        ],
       [ 1.81098674,  5.17270135, -0.46878789,  2.44997251,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  2.66485989,  0.80935387,  1.        ],
       [-2.21015722,  8.2176402 , 12.69328115,  0.50644607,  2.        ],
       [ 2.91161235,  7.90337695, 11.79840961,  4.86816939,  1.        ]])

In [ ]:
random_test_data.shape

(1000, 5)

In [ ]:
# Step 3: Export to CSV
#np.savetxt("Random-Test-From-NP.csv", random_test_data, fmt = "%s", delimiter= = ",")

In [ ]:
# Import back CSV into python
# np.genfromtxt("Random-Test-From-NP.csv", delimiter= = ",")